### ISSUE TITLE
Column 'name' cannot be null

### ISSUE THREAD

**Issue by moltar** [nebev/mautic-sms-reader#1]
Hi,

I'm getting the following error, when I'm trying to install the plugin.

> [2017-04-18 03:53:02] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO plugins (name, description, is_missing, bundle, version, author) VALUES (?, ?, ?, ?, ?, ?)' with params [null, null, 0, "SmsreaderBundle", null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null" at /var/www/mautic/mautic-2.7.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO plugins (name, description, is_missing, bundle, version, author) VALUES (?, ?, ?, ?, ?, ?)' with params [null, null, 0, \"SmsreaderBundle\", null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null at /var/www/mautic/mautic-2.7.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null at /var/www/mautic/mautic-2.7.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null at /var/www/mautic/mautic-2.7.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

Mautic Version: 2.7.1

Steps to reproduce:

1. Checkout plugin into plugins/
2. Go to gear -> plugins
3. Click "Install/Upgrade Plugin"
4. Now nothing happens, and the log produces the error.

**Comment by moltar** [comment]
Never mind. The folder name was not exactly right. I had `SmsReaderBundle` instead of `SmsreaderBundle`.

**Comment by nebev** [comment]
No worries. Glad to hear you sorted it. Please let me know if this works for you and if it's useful!
