### ISSUE TITLE
Not showing in Mautic Plugins 

### ISSUE THREAD

**Issue by Zoronto** [nebev/mautic-sms-reader#2]
So i thought of using this plugin as we have mautic configured with twilio and want the unsubscribe data to flow back to mautic.

Followed all the procedures, cleared cache . 

Still unable to see the plugin in the mautic plugin dashboard.

We are using mautic version 2.10.0.

Any idea what can help?

**Comment by nebev** [comment]
I'll test with Mautic 2.11.0 shortly and report back

**Comment by nebev** [comment]
Hey. I can't replicate the issue on 2.11.0
I added it successfully in a brand new mautic install.
See video here: https://youtu.be/AtDgR1KlQ4g

Is there any more information you can give? Did you definitely rename the folder as specified in the README?

**Comment by Zoronto** [comment]
Yes it works now. There was some problem with permissions i guess. Thanks for the time. The plugin is really awesome.
